name: Upload to DAFNI

on:
  release:
    types: [published]

jobs:
  release:
    name: Upload to DAFNI
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Docker Build
        run: docker build -t ssp .

      - name: Compress docker image
        run: docker save ssp | gzip > ssp.tar.gz

      - name: Set tag as env
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Upload to DAFNI
        uses: dafnifacility/dafni-model-uploader@v1.11
        with:
          definition-path: './model-definition.yml'
          image-path: ./ssp.tar.gz
          username: ${{ secrets.DAFNI_SERVICE_ACCOUNT_USERNAME }}
          password: ${{ secrets.DAFNI_SERVICE_ACCOUNT_PASSWORD }}
          version-message: ${{ env.TAG }}
          parent-model: "eb1c1484-4cd1-4c5b-bb00-53ebe1d6e7d6"
